name: Rust

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos, windows]
        include:
          - build: linux
            os: ubuntu-18.04
            rust: nightly
            target: x86_64-unknown-linux-musl
            exe-name: truss_solver-x86_64-unknown-linux-musl
          - build: macos
            os: macos-latest
            rust: nightly
            target: x86_64-apple-darwin
            exe-name: truss_solver-x86_64-apple-darwin
          - build: windows
            os: windows-2019
            rust: nightly-x86_64-msvc
            target: x86_64-pc-windows-msvc
            exe-name: truss_solver-x86_64-pc-windows-msvc.exe
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --verbose --release --target ${{ matrix.target }}
        env:
          RUST_BACKTRACE: 1

      - name: Strip binary (linux and macos)
        if: matrix.build == 'linux' || matrix.build == 'macos'
        run: strip "target/${{ matrix.target }}/release/truss_solver"

      - name: Copy Artifect to Workdir
        shell: bash
        run: |
          if [ "${{ matrix.build }}" = "windows" ]; then
            cp "./target/${{ matrix.target }}/release/truss_solver.exe" ./${{ matrix.exe-name }}
          else
            cp "./target/${{ matrix.target }}/release/truss_solver" ./${{ matrix.exe-name }}
          fi
          
      - name: Create Release
        if: ${{ github.event_name == 'push' }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: true
          prerelease: false
          files: |
            ./${{ matrix.exe-name }}
            
